import type { ParamValues } from "@/params";

export interface TextPreset {
	id: string;
	name: string;
	/** Param overrides applied on top of the default text element params. */
	params: ParamValues;
	/** Preview swatch colors. */
	swatch: [string, string];
}

export const TEXT_PRESETS: TextPreset[] = [
	{
		id: "default",
		name: "Default",
		params: {},
		swatch: ["#ffffff", "#111827"],
	},
	{
		id: "bold-title",
		name: "Bold Title",
		params: {
			content: "TITLE",
			fontSize: 42,
			fontWeight: "bold",
			letterSpacing: 3,
		},
		swatch: ["#ffffff", "#374151"],
	},
	{
		id: "subtitle",
		name: "Subtitle",
		params: {
			content: "A subtle subtitle",
			fontSize: 20,
			letterSpacing: 6,
			"shadow.enabled": true,
			"shadow.color": "#000000",
			"shadow.blur": 6,
			"shadow.offsetX": 0,
			"shadow.offsetY": 2,
		},
		swatch: ["#e5e7eb", "#1f2937"],
	},
	{
		id: "outline",
		name: "Outline",
		params: {
			content: "OUTLINE",
			fontSize: 36,
			fontWeight: "bold",
			color: "#ffffff",
			"stroke.enabled": true,
			"stroke.color": "#000000",
			"stroke.width": 6,
		},
		swatch: ["#ffffff", "#000000"],
	},
	{
		id: "neon",
		name: "Neon",
		params: {
			content: "NEON",
			fontSize: 38,
			fontWeight: "bold",
			color: "#ffffff",
			"glow.enabled": true,
			"glow.color": "#22d3ee",
			"glow.radius": 24,
		},
		swatch: ["#22d3ee", "#0e7490"],
	},
	{
		id: "golden",
		name: "Golden",
		params: {
			content: "Golden",
			fontSize: 38,
			fontWeight: "bold",
			color: "#fff7cc",
			"gradient.enabled": true,
			"gradient.color": "#f59e0b",
			"gradient.angle": 90,
			"shadow.enabled": true,
			"shadow.color": "#78350f",
			"shadow.blur": 4,
			"shadow.offsetX": 0,
			"shadow.offsetY": 2,
		},
		swatch: ["#fff7cc", "#f59e0b"],
	},
	{
		id: "hard-shadow",
		name: "Hard Shadow",
		params: {
			content: "POP!",
			fontSize: 40,
			fontWeight: "bold",
			color: "#fde047",
			"shadow.enabled": true,
			"shadow.color": "#000000",
			"shadow.blur": 0,
			"shadow.offsetX": 6,
			"shadow.offsetY": 6,
		},
		swatch: ["#fde047", "#000000"],
	},
	{
		id: "caption-box",
		name: "Caption",
		params: {
			content: "Auto caption style",
			fontSize: 18,
			"background.enabled": true,
			"background.color": "#000000",
			"background.cornerRadius": 20,
			"background.paddingX": 24,
			"background.paddingY": 12,
		},
		swatch: ["#000000", "#4b5563"],
	},
	{
		id: "karaoke",
		name: "Karaoke",
		params: {
			content: "Sing along!",
			fontSize: 22,
			fontWeight: "bold",
			color: "#ffffff",
			"background.enabled": true,
			"background.color": "#fe2c55",
			"background.cornerRadius": 30,
			"background.paddingX": 28,
			"background.paddingY": 12,
		},
		swatch: ["#fe2c55", "#7f1d1d"],
	},
	{
		id: "serif-elegant",
		name: "Elegant",
		params: {
			content: "Elegant",
			fontSize: 34,
			fontFamily: "Georgia",
			fontStyle: "italic",
			letterSpacing: 2,
			color: "#f5f5f4",
		},
		swatch: ["#f5f5f4", "#78716c"],
	},
	{
		id: "mono-code",
		name: "Mono",
		params: {
			content: "monospace_01",
			fontSize: 20,
			fontFamily: "Courier New",
			color: "#4ade80",
			"background.enabled": true,
			"background.color": "#0f172a",
			"background.cornerRadius": 8,
			"background.paddingX": 20,
			"background.paddingY": 10,
		},
		swatch: ["#4ade80", "#0f172a"],
	},
	{
		id: "neon-pink",
		name: "Neon Pink",
		params: {
			content: "VIBE",
			fontSize: 40,
			fontWeight: "bold",
			color: "#ffffff",
			"glow.enabled": true,
			"glow.color": "#ec4899",
			"glow.radius": 28,
			"stroke.enabled": true,
			"stroke.color": "#831843",
			"stroke.width": 2,
		},
		swatch: ["#ec4899", "#831843"],
	},
	{
		id: "variety",
		name: "Variety",
		swatch: ["#ffd54a", "#ff8a3c"],
		params: {
			content: "综艺花字",
			fontSize: 58,
			fontWeight: "900",
			color: "#ffd54a",
			letterSpacing: 2,
			"stroke.enabled": true,
			"stroke.color": "#1a1a1a",
			"stroke.width": 6,
		},
	},
	{
		id: "cinema-subtitle",
		name: "Cinema Subtitle",
		swatch: ["#ffffff", "#111111"],
		params: {
			content: "电影字幕样式",
			fontSize: 36,
			color: "#ffffff",
			letterSpacing: 4,
			"background.enabled": true,
			"background.color": "#000000",
			"background.cornerRadius": 6,
			"background.paddingX": 18,
			"background.paddingY": 8,
		},
	},
	{
		id: "fluorescent",
		name: "Fluorescent",
		swatch: ["#39ff14", "#003b00"],
		params: {
			content: "荧光绿标题",
			fontSize: 54,
			fontWeight: "bold",
			color: "#39ff14",
			letterSpacing: 3,
			"glow.enabled": true,
			"glow.color": "#39ff14",
			"glow.radius": 18,
		},
	},
];
