import { buildStickerId } from "../sticker-id";
import type {
	StickerBrowseResult,
	StickerItem,
	StickerProvider,
	StickerSearchResult,
} from "../types";

const EMOJI_PROVIDER_ID = "emoji";
const EMOJI_RENDER_SIZE = 128;

interface EmojiGroup {
	name: string;
	emojis: Array<[string, string]>;
}

/**
 * A curated emoji set. Each entry is [glyph, search name]. Rendered as SVG
 * data URLs so stickers resolve like any other image source.
 */
const EMOJI_GROUPS: EmojiGroup[] = [
	{
		name: "Smileys",
		emojis: [
			["😀", "grinning face happy"],
			["😃", "smiley happy"],
			["😄", "smile happy eyes"],
			["😁", "grin beam"],
			["😂", "joy tears laugh"],
			["🤣", "rofl rolling laughing"],
			["😊", "blush smile"],
			["😇", "innocent halo angel"],
			["🙂", "slight smile"],
			["😉", "wink"],
			["😍", "heart eyes love"],
			["🥰", "love hearts"],
			["😘", "kiss"],
			["😎", "cool sunglasses"],
			["🤩", "star struck"],
			["🥳", "party celebration"],
			["😏", "smirk"],
			["😐", "neutral"],
			["😴", "sleep zzz"],
			["😭", "sob cry"],
			["😡", "angry rage"],
			["🤯", "mind blown exploding head"],
			["🥱", "yawn"],
			["🤔", "thinking"],
			["🤗", "hug"],
			["🤫", "shush quiet"],
			["🤭", "giggle oops"],
			["😬", "grimace awkward"],
			["🫠", "melting"],
		],
	},
	{
		name: "Gestures",
		emojis: [
			["👍", "thumbs up like ok"],
			["👎", "thumbs down dislike"],
			["👌", "ok perfect"],
			["✌️", "peace victory"],
			["🤞", "fingers crossed luck"],
			["🤟", "love you"],
			["🤘", "rock horns"],
			["👏", "clap applause"],
			["🙌", "raised hands hooray"],
			["🤝", "handshake deal"],
			["🙏", "pray thanks please"],
			["💪", "muscle strong flex"],
			["👀", "eyes look watch"],
			["🫶", "heart hands love"],
			["👋", "wave hello bye"],
			["✋", "hand stop high five"],
		],
	},
	{
		name: "Hearts",
		emojis: [
			["❤️", "red heart love"],
			["🧡", "orange heart"],
			["💛", "yellow heart"],
			["💚", "green heart"],
			["💙", "blue heart"],
			["💜", "purple heart"],
			["🖤", "black heart"],
			["🤍", "white heart"],
			["💖", "sparkling heart"],
			["💘", "heart arrow cupid"],
			["💔", "broken heart"],
			["💯", "hundred perfect score"],
			["🔥", "fire hot lit"],
			["✨", "sparkles shine"],
			["⭐", "star favorite"],
			["🌟", "glowing star"],
		],
	},
	{
		name: "Animals",
		emojis: [
			["🐶", "dog puppy"],
			["🐱", "cat kitten"],
			["🐭", "mouse"],
			["🐹", "hamster"],
			["🐰", "rabbit bunny"],
			["🦊", "fox"],
			["🐻", "bear"],
			["🐼", "panda"],
			["🐨", "koala"],
			["🐯", "tiger"],
			["🦁", "lion"],
			["🐮", "cow"],
			["🐷", "pig"],
			["🐸", "frog"],
			["🐵", "monkey"],
			["🦄", "unicorn"],
			["🐙", "octopus"],
			["🦋", "butterfly"],
			["🐢", "turtle"],
			["🐧", "penguin"],
		],
	},
	{
		name: "Food",
		emojis: [
			["🍏", "green apple"],
			["🍎", "red apple"],
			["🍌", "banana"],
			["🍓", "strawberry"],
			["🍉", "watermelon"],
			["🍕", "pizza"],
			["🍔", "burger"],
			["🍟", "fries"],
			["🌮", "taco"],
			["🍣", "sushi"],
			["🍜", "noodles ramen"],
			["🍩", "donut"],
			["🍪", "cookie"],
			["🎂", "cake birthday"],
			["🍦", "ice cream"],
			["☕", "coffee"],
			["🧋", "bubble tea boba"],
			["🍺", "beer"],
			["🥂", "champagne cheers"],
		],
	},
	{
		name: "Celebrate",
		emojis: [
			["🎉", "party popper celebrate"],
			["🎊", "confetti ball"],
			["🎈", "balloon"],
			["🪅", "pinata"],
			["🎯", "dart target hit"],
			["🏆", "trophy win"],
			["🥇", "gold medal first"],
			["🎖️", "medal honor"],
		],
	},
	{
		name: "Symbols",
		emojis: [
			["✅", "check mark yes done"],
			["❌", "cross no wrong"],
			["➕", "plus add"],
			["➖", "minus subtract"],
			["❓", "question"],
			["❗", "exclamation important"],
			["💥", "boom collision"],
			["🆗", "ok button"],
			["🔝", "top up"],
			["🆒", "cool button"],
		],
	},
	{
		name: "Music",
		emojis: [
			["🎵", "music note"],
			["🎶", "notes melody"],
			["🎹", "piano keyboard"],
			["🎸", "guitar"],
			["🎻", "violin"],
			["🥁", "drum"],
			["🎺", "trumpet"],
			["🪗", "accordion"],
		],
	},
	{
		name: "Sports",
		emojis: [
			["🎾", "tennis"],
			["🏈", "american football"],
			["🏐", "volleyball"],
			["🏓", "ping pong table tennis"],
			["🏒", "hockey"],
			["⛳", "golf"],
			["🥊", "boxing"],
			["🛹", "skateboard"],
			["🎿", "ski"],
			["🏄", "surfing"],
		],
	},
	{
		name: "Nature",
		emojis: [
			["🌸", "cherry blossom sakura"],
			["🌷", "tulip"],
			["🌺", "hibiscus"],
			["🌻", "sunflower"],
			["🌼", "blossom daisy"],
			["🌿", "herb leaf"],
			["🍀", "clover luck"],
			["🌴", "palm tree"],
			["🌵", "cactus"],
			["🍁", "maple leaf autumn"],
			["💧", "droplet water"],
			["☂️", "umbrella rain"],
		],
	},
	{
		name: "Faces 2",
		emojis: [
			["🤠", "cowboy hat"],
			["🥸", "disguise"],
			["🤓", "nerd geek"],
			["🤢", "sick green"],
			["🥴", "woozy dizzy"],
			["🤪", "zany crazy"],
			["🤬", "cursing angry"],
			["😷", "mask sick"],
		],
	},
	{
		name: "Animals 2",
		emojis: [
			["🦈", "shark"],
			["🐬", "dolphin"],
			["🐝", "bee"],
			["🦉", "owl"],
			["🦖", "trex dinosaur"],
			["🦕", "saurus dinosaur"],
			["🦎", "lizard"],
		],
	},
	{
		name: "Zodiac",
		emojis: [
			["♈", "aries"],
			["♉", "taurus"],
			["♊", "gemini"],
			["♋", "cancer"],
			["♌", "leo"],
			["♍", "virgo"],
			["♎", "libra"],
			["♏", "scorpio"],
			["♐", "sagittarius"],
			["♑", "capricorn"],
			["♒", "aquarius"],
			["♓", "pisces"],
			["⛎", "ophiuchus"],
		],
	},
	{
		name: "Faces 3",
		emojis: [
			["😊", "blushing smile"],
			["😇", "innocent halo"],
			["🙂", "slight smile"],
			["😉", "wink"],
			["😌", "relieved content"],
			["😍", "heart eyes love"],
			["😘", "kiss cheek"],
			["😗", "kissing face"],
			["🥲", "smiling tear happy sad"],
			["😈", "devil smiling imp"],
			["👿", "angry devil imp"],
			["🤡", "clown"],
			["💀", "skull dead"],
			["👻", "ghost boo"],
			["👽", "alien ufo"],
			["🤖", "robot"],
		],
	},
	{
		name: "Nature 2",
		emojis: [
			["🌍", "earth globe"],
			["🌎", "americas globe"],
			["🌏", "asia globe"],
			["🌙", "crescent moon"],
			["🌚", "new moon face"],
			["🌝", "full moon face"],
			["⭐", "star"],
			["🌟", "glowing star"],
			["✨", "sparkles"],
			["☄️", "comet"],
			["💥", "collision boom"],
			["🔥", "fire"],
			["🌪️", "tornado"],
			["🌴", "palm tree"],
			["🌵", "cactus"],
			["🎄", "christmas tree"],
		],
	},
	{
		name: "Time",
		emojis: [
			["⏰", "alarm clock"],
			["⏱️", "stopwatch"],
			["⏲️", "timer"],
			["🕰️", "mantelpiece clock"],
			["🕐", "one oclock"],
			["📅", "calendar"],
			["📆", "tear-off calendar"],
			["🗓️", "spiral calendar"],
			["📈", "chart increasing"],
			["📉", "chart decreasing"],
			["📊", "bar chart"],
			["⌛", "hourglass done"],
			["⏳", "hourglass not done"],
		],
	},
	{
		name: "Weather",
		emojis: [
			["🌧️", "cloud with rain"],
			["⛈️", "thunderstorm"],
			["🌨️", "cloud with snow"],
			["❄️", "snowflake"],
			["🌫️", "fog"],
			["🌪️", "tornado"],
			["🌈", "rainbow"],
			["☀️", "sun"],
			["🌤️", "sun behind cloud"],
			["⛅", "partly cloudy"],
			["☁️", "cloud"],
			["💨", "dash wind"],
			["🌊", "water wave"],
			["💧", "droplet"],
			["🔥", "fire"],
			["❄️", "snow"],
		],
	},
	{
		name: "Buildings",
		emojis: [
			["🏰", "castle european"],
			["🏯", "japanese castle"],
			["🏟️", "stadium"],
			["🏛️", "classical building"],
			["🏗️", "construction crane"],
			["🏘️", "houses"],
			["🏢", "office building"],
			["🏪", "convenience store"],
			["🏫", "school"],
			["🏥", "hospital"],
			["🏦", "bank"],
			["⛪", "church"],
			["🕌", "mosque"],
			["🛕", "hindu temple"],
			["🕍", "synagogue"],
			["⛩️", "shinto shrine torii"],
		],
	},
	{
		name: "Clothes",
		emojis: [
			["👕", "t-shirt"],
			["👖", "jeans pants"],
			["🧥", "coat jacket"],
			["👗", "dress"],
			["👚", "womans clothes blouse"],
			["🩱", "one-piece swimsuit"],
			["🩳", "shorts"],
			["🧦", "socks"],
			["🧢", "billed cap"],
			["🎩", "top hat"],
			["🎓", "graduation cap"],
			["👑", "crown"],
			["🎒", "backpack school"],
			["👜", "handbag"],
			["👓", "glasses"],
			["🧣", "scarf"],
		],
	},
	{
		name: "Flowers",
		emojis: [
			["🌸", "cherry blossom sakura"],
			["🌺", "hibiscus"],
			["🌻", "sunflower"],
			["🌹", "rose"],
			["🥀", "wilted flower"],
			["🌷", "tulip"],
			["🌼", "blossom daisy"],
			["💐", "bouquet"],
			["🏵️", "rosette"],
			["🌿", "herb leaf"],
			["🍀", "four leaf clover luck"],
			["🍁", "maple leaf"],
			["🍂", "fallen leaf autumn"],
			["🌱", "seedling sprout"],
			["🪷", "lotus"],
			["🪴", "potted plant"],
		],
	},
	{
		name: "Hands",
		emojis: [
			["👍", "thumbs up like"],
			["👎", "thumbs down dislike"],
			["👌", "ok hand"],
			["✌️", "victory peace hand"],
			["🤞", "crossed fingers luck"],
			["🤟", "love you gesture"],
			["🤘", "sign of the horns rock"],
			["👏", "clapping hands applause"],
			["🙌", "raising hands celebrate"],
			["🙏", "folded hands thanks pray"],
			["🤝", "handshake deal"],
			["💪", "flexed biceps strong muscle"],
			["🖐️", "hand fingers spread"],
			["👋", "waving hand hello"],
			["🤙", "call me hand shaka"],
			["✊", "raised fist power"],
		],
	},
	{
		name: "Food 2",
		emojis: [
			["🍜", "steaming noodle bowl ramen"],
			["🍣", "sushi"],
			["🍩", "doughnut donut"],
			["🍪", "cookie"],
			["🎂", "birthday cake"],
			["🧁", "cupcake"],
			["🍫", "chocolate"],
			["🍿", "popcorn movie"],
			["🧋", "bubble tea boba"],
			["☕", "coffee tea hot"],
			["🧊", "ice cube"],
			["🍉", "watermelon"],
			["🍓", "strawberry"],
			["🥑", "avocado"],
			["🌶️", "hot pepper spicy"],
			["🥕", "carrot"],
		],
	},
	{
		name: "Animals 3",
		emojis: [
			["🐼", "panda"],
			["🦊", "fox"],
			["🐻", "bear"],
			["🐨", "koala"],
			["🐯", "tiger face"],
			["🦁", "lion"],
			["🐮", "cow face"],
			["🐷", "pig face"],
			["🐸", "frog"],
			["🐵", "monkey face"],
			["🦄", "unicorn"],
			["🐙", "octopus"],
			["🦋", "butterfly"],
			["🐝", "honeybee bee"],
			["🐬", "dolphin"],
			["🐢", "turtle tortoise"],
		],
	},
	{
		name: "Symbols 2",
		emojis: [
			["❤️", "red heart love"],
			["🧡", "orange heart"],
			["💛", "yellow heart"],
			["💚", "green heart"],
			["💙", "blue heart"],
			["💜", "purple heart"],
			["🖤", "black heart"],
			["💯", "hundred points perfect"],
			["✨", "sparkles"],
			["⚡", "lightning bolt high voltage"],
			["🔥", "fire lit hot"],
			["🌈", "rainbow"],
			["☀️", "sun sunny"],
			["🌙", "crescent moon night"],
			["⭐", "star"],
			["💤", "zzz sleep"],
		],
	},
	{
		name: "Emotions",
		emojis: [
			["🥰", "smiling face with hearts love"],
			["😘", "face blowing a kiss"],
			["😜", "winking face tongue"],
			["🤪", "zany face crazy"],
			["🥳", "partying face celebration"],
			["😎", "smiling face with sunglasses cool"],
			["🤓", "nerd face glasses"],
			["🥺", "pleading face puppy"],
			["😭", "loudly crying sad"],
			["😱", "face screaming fear"],
			["🤯", "exploding head mind blown"],
			["🥱", "yawning face tired"],
			["😴", "sleeping face zzz"],
			["🤒", "face with thermometer sick"],
			["🤢", "nauseated face green"],
			["🤠", "cowboy hat face"],
			["🥸", "disguised face incognito"],
			["🤫", "shushing face quiet"],
			["🤔", "thinking face hmm"],
			["🤭", "face with hand over mouth"],
			["🫡", "saluting face respect"],
			["🫠", "melting face"],
		],
	},
	{
		name: "Activities",
		emojis: [
			["🎉", "party popper celebrate"],
			["🎊", "confetti ball"],
			["🎈", "balloon"],
			["🎁", "gift present"],
			["🏆", "trophy winner"],
			["🥇", "first place gold medal"],
			["🎯", "bullseye target dart"],
			["🎲", "game die dice"],
			["🎮", "video game controller"],
			["🎸", "guitar rock"],
			["🎤", "microphone karaoke sing"],
			["🎧", "headphones music"],
			["🎬", "clapper board movie"],
			["🎨", "artist palette paint"],
			["🎹", "musical keyboard piano"],
			["🥁", "drum"],
			["🪩", "mirror ball disco"],
			["🎳", "bowling"],
			["🏀", "basketball"],
			["⚽", "soccer ball football"],
		],
	},
	{
		name: "Travel",
		emojis: [
			["✈️", "airplane fly travel"],
			["🚗", "automobile car"],
			["🚕", "taxi"],
			["🚌", "bus"],
			["🚂", "locomotive train"],
			["🚢", "ship boat"],
			["🛴", "kick scooter"],
			["🗺️", "world map"],
			["🧭", "compass navigation"],
			["🏝️", "desert island beach"],
			["🏖️", "beach with umbrella"],
			["⛰️", "mountain"],
			["🌋", "volcano"],
			["🏕️", "camping tent"],
			["🏠", "house home"],
			["🏢", "office building"],
			["🗼", "tokyo tower landmark"],
			["🗽", "statue of liberty"],
			["🌅", "sunrise"],
			["🚀", "rocket launch"],
		],
	},
	{
		name: "Objects",
		emojis: [
			["💎", "gem diamond"],
			["⏰", "alarm clock"],
			["📚", "books study"],
			["✏️", "pencil"],
			["📎", "paperclip"],
			["🔑", "key"],
			["🔒", "locked"],
			["📱", "mobile phone"],
			["💻", "laptop computer"],
			["🖥️", "desktop computer"],
			["📷", "camera photo"],
			["🔍", "magnifying glass search"],
			["💡", "light bulb idea"],
			["🔋", "battery"],
			["🧸", "teddy bear"],
			["🛒", "shopping cart"],
			["💰", "money bag"],
			["💳", "credit card"],
			["✉️", "envelope mail"],
			["📦", "package box"],
		],
	},
	{
		name: "Items",
		emojis: [
			["⚽", "soccer football"],
			["🏀", "basketball"],
			["🎮", "game controller"],
			["🎧", "headphones music"],
			["🎤", "microphone sing"],
			["🎬", "clapper movie film"],
			["📸", "camera photo"],
			["💻", "laptop computer"],
			["📱", "phone mobile"],
			["💡", "light bulb idea"],
			["📚", "books study"],
			["✏️", "pencil write"],
			["🎨", "art palette"],
			["🎁", "gift present"],
			["🚀", "rocket launch"],
			["✈️", "plane travel"],
			["🚗", "car"],
			["🏝️", "island vacation"],
			["🌈", "rainbow"],
			["☀️", "sun sunny"],
			["🌙", "moon night"],
			["☁️", "cloud"],
			["⚡", "lightning zap"],
			["❄️", "snow cold"],
		],
	},
];

const ALL_EMOJIS: Array<{ glyph: string; name: string; group: string }> =
	EMOJI_GROUPS.flatMap((group) =>
		group.emojis
			.filter(([glyph]) => !glyph.includes(" "))
			.map(([glyph, name]) => ({ glyph, name, group: group.name })),
	);

function buildEmojiSvgDataUrl({ glyph }: { glyph: string }): string {
	const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${EMOJI_RENDER_SIZE}" height="${EMOJI_RENDER_SIZE}" viewBox="0 0 ${EMOJI_RENDER_SIZE} ${EMOJI_RENDER_SIZE}"><text x="50%" y="54%" dominant-baseline="middle" text-anchor="middle" font-size="${Math.round(EMOJI_RENDER_SIZE * 0.8)}">${glyph}</text></svg>`;
	return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

function toStickerItem({
	glyph,
	name,
	group,
}: {
	glyph: string;
	name: string;
	group: string;
}): StickerItem {
	return {
		id: buildStickerId({
			providerId: EMOJI_PROVIDER_ID,
			providerValue: glyph,
		}),
		provider: EMOJI_PROVIDER_ID,
		name: name.charAt(0).toUpperCase() + name.slice(1),
		previewUrl: buildEmojiSvgDataUrl({ glyph }),
		metadata: { group, keywords: name },
	};
}

function emojiFromStickerId({ stickerId }: { stickerId: string }): string {
	const separatorIndex = stickerId.indexOf(":");
	const value =
		separatorIndex === -1 ? "" : stickerId.slice(separatorIndex + 1);
	return decodeURIComponent(value);
}

export const emojiProvider: StickerProvider = {
	id: EMOJI_PROVIDER_ID,
	async search({ query, options }) {
		const limit = options?.limit ?? 100;
		const normalized = query.trim().toLowerCase();
		const matches = normalized
			? ALL_EMOJIS.filter(
					(entry) =>
						entry.name.includes(normalized) ||
						entry.group.toLowerCase().includes(normalized) ||
						entry.glyph === query.trim(),
				)
			: ALL_EMOJIS;

		const items = matches
			.slice(0, limit)
			.map((entry) => toStickerItem(entry));
		return { items, total: matches.length, hasMore: matches.length > limit };
	},
	async browse({ options }) {
		const limit = options?.limit ?? 200;
		const sections = EMOJI_GROUPS.map((group) => ({
			id: `emoji-group-${group.name.toLowerCase()}`,
			title: group.name,
			layout: "grid" as const,
			items: group.emojis
				.filter(([glyph]) => !glyph.includes(" "))
				.slice(0, limit)
				.map(([glyph, name]) => toStickerItem({ glyph, name, group: group.name })),
			hasMore: false,
		}));
		return { sections };
	},
	resolveUrl({ stickerId }) {
		return buildEmojiSvgDataUrl({
			glyph: emojiFromStickerId({ stickerId }),
		});
	},
};
